#!/dis/sh
(pat files)=$*
upat=`{echo $pat | sed '
s,AE,(AE|Æ|E),g
s,Ae,(Ae|Æ|E),g
s,Æ,(AE|Ae|Æ|E),g
s,A,[AÀÁÂÃÄÅĂĄǍǞǠΑА],g
s,C,[CÇĆĈĊČ],g
s,E,[EÈÉÊËĒĔĖĘĚΕ],g
s,I,[IÌÍÎÏĨĪĬĮİĲǏΙΪ],g
s,N,[NÑŃŅŇǊ],g
s,O,[OÒÓÔÕÖØŌŎŒƢǑǪǬΟΩО],g
s,U,[UÙÚÛÜŨŪŬŮŲǓǕǗǙǛΥΫУ],g
s,(ae|æ),(ae|æ|e),g
s,a,[aàáâãäåāąǎǟǡαа],g
s,c,[cçćĉċč],g
s,e,[æeèéêëēĕėęěε],g
s,i,[iìíîïĩīĭįĳǐιϊ],g
s,n,[nñńņňǌ],g
s,o,[oòóôõöøōŏœƣǒǫǭοωо],g
s,u,[uùúûüũūŭůųǔǖǘǚǜυϋу],g
'}
grep $upat $files
